server:
  port: 8080
  servlet:
    context-path: /api
dashscope:
  api:
#    key: ${DASHSCOPE_API_KEY:}
  model: qwen-turbo
spring:
  application:
    name: workWeek03 开发环境
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload:
    path: ./uploads
app:
  name: "spring-boot-demo"
  version: "1.0.0"
  description: "Spring Boot Demo"
  database:
    host: localhost
aliyun:
  sms:
    # 是否启用短信服务
    enabled: true
    # 服务端点配置
    endpoint: dypnsapi.aliyuncs.com
    region-id: cn-hangzhou
    # 敏感信息：建议用环境变量覆盖，不写死在配置中
#    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
#    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:}
    # 赠送签名（见 1.3 赠送签名配置）
    sign-name: "速通互联验证码"
    # 赠送模板 CODE（见 1.4 赠送模板配置）
    template-code: "100001"
    # 方案名称，可选，不填为默认方案
    scheme-name: